Id: LutzRoeder.Netron
Version: 4.6.6
Name: Netron
Publisher: Lutz Roeder
AppMoniker: netron
Description: Visualizer for neural network, deep learning, and machine learning models
License: Copyright (c) Lutz Roeder
Homepage: https://github.com/lutzroeder/netron
Installers:
  - Arch: x86
    InstallerType: nullsoft
    Url: https://github.com/lutzroeder/netron/releases/download/v4.6.6/Netron-Setup-4.6.6.exe
    Sha256: C6F7AE61CB51F2357E9710D688D6514C6E82A8CC98531C28ACD05E1637E07F92
